[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chill-sharp-py-client"
version = "1.0.73"
description = "Python client for generic ChillSharp services"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "requests>=2.31.0",
]
authors = [
  { name = "Andrea Piovesan" }
]
license = { text = "AGPL-3.0-or-later" }
keywords = ["chillsharp", "client", "rest", "ef-core", "python"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
  "Operating System :: OS Independent",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["chillsharp_py_client*"]
